In [1]:
import numpy as np
import tensorflow as tf

/Users/chenwu/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:526: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/Users/chenwu/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:527: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/Users/chenwu/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:528: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/Users/chenwu/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework

In [47]:
import csv

bb_list = []
with open('./bounding_boxes.csv') as csvfile:
    readCSV = csv.reader(csvfile, delimiter=',')
    for row in readCSV:
        bb_list.append(row)
        
bb_list.pop(0)

image_id = {} 
for j in range(1,9767):
    image_id[j] = np.array([0,0,0,0,0])
    
for i in range(len(bb_list)):
    for j in range(len(bb_list[i])):
        #print(bb_list[i][j])
        bb_list[i][j] = float(bb_list[i][j])
        bb_list[i][0] = int(bb_list[i][0])

In [55]:
from tqdm import tqdm
for idy in tqdm(image_id.keys()):
    num = []
    for image in bb_list:
        if image[0] == idy:
            xc = image[1]+image[3]/2
            yc = image[2]+image[4]/2
            wc = image[3]
            hc = image[4]
            x = xc*15/720 - int(xc*15/720)
            y = yc*10/480 - int(yc*10/480)
            w = wc / 48
            h = hc / 48
            num.append(np.array([1, x,y,w,h]))
            image_id[idy]= num

100%|██████████| 9766/9766 [00:13<00:00, 701.74it/s]


In [80]:
image_id

{1: [array([1.        , 0.38541667, 0.40625   , 1.16666667, 0.79166667])],
 2: [array([1.        , 0.75      , 0.51041667, 2.52083333, 2.70833333])],
 3: [array([1.        , 0.05208333, 0.875     , 1.875     , 1.8125    ])],
 4: array([0, 0, 0, 0, 0]),
 5: [array([1.        , 0.0625    , 0.33333333, 2.14583333, 0.4375    ])],
 6: [array([1.        , 0.57291667, 0.86458333, 0.70833333, 0.54166667])],
 7: [array([1.        , 0.71875   , 0.08333333, 5.41666667, 2.89583333])],
 8: array([0, 0, 0, 0, 0]),
 9: [array([1.        , 0.72916667, 0.15625   , 1.3125    , 0.75      ])],
 10: array([0, 0, 0, 0, 0]),
 11: [array([1.        , 0.        , 0.34375   , 1.5625    , 1.54166667]),
  array([1.    , 0.3125, 0.8125, 0.4375, 0.4375])],
 12: array([0, 0, 0, 0, 0]),
 13: [array([1.        , 0.3125    , 0.10416667, 0.60416667, 0.85416667]),
  array([1.        , 0.19791667, 0.25      , 0.75      , 0.64583333]),
  array([1.        , 0.375     , 0.4375    , 0.5625    , 0.47916667])],
 14: array([0, 0

In [71]:
(444.5+75/2 )*15/720

10.041666666666666

In [62]:
int((442.5+75/2 )*15/720)

10

In [64]:
xc = 442.5+75/2

In [66]:
xc*15

7200.0